---

packages:
  apt_install:
  - apt-transport-https
  - arptables
  - ca-certificates
  - curl
  - dnsutils
  - ethtool
  - git
  - gnupg-agent
  - gnupg2
  - hdparm
  - iperf3
  - iputils-ping
  - ipvsadm
  - jq
  - lvm2
  - net-tools
  - netcat
  - nfs-common
  - nmap
  - ntpdate
  - psmisc
  - python3
  - python3-openssl
  - python3-pip
  - rclone
  - rsync
  - socat
  - software-properties-common
  - traceroute
  - unattended-upgrades
  - unzip
  - vim
  - tmux
  - bat
  - delta
  - smartmontools
  - ceph-common
  apt_remove:
  - apparmor
  - apport
  - bcache-tools
  - btrfs-progs
  - byobu
  - cloud-init
  - cloud-guest-utils
  - cloud-initramfs-copymods
  - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - fwupd
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - open-vm-tools
  - plymouth
  - plymouth-theme-ubuntu-text
  - popularity-contest
    #- snapd
  - sosreport
  - ubuntu-advantage-tools
  - ufw
  
