---

all:
  children:
    # Master group, do not change the 'master' name
    # hosts should match the filenames in 'host_vars'
    master:
      hosts:
        rocione:
        rocitwo:
        rocithree:
    # Worker group, do not change the 'worker' name
    # hosts should match the filenames in 'host_vars'
    worker:
      hosts:
    # Storage group, these are my NAS devices
    # hosts should match the filenames in 'host_vars'
    storage:
      hosts:
