---

- include: user.yml
  tags:
  - user

- include: packages.yml
  tags:
  - packages

    # - include: kernel.yml
    #   tags:
    #   - kernel

- include: podman.yml
  tags:
  - podman

- include: unattended-upgrades.yml
  tags:
  - unattended-upgrades

- include: rsyslog.yml
  when:
  - rsyslog.enabled is defined 
  - rsyslog.enabled
  tags:
  - rsyslog
