---

- name: logind | restart systemd service
  systemd:
    name: systemd-logind.service
    daemon_reload: yes
    enabled: yes
    state: restarted
  listen: restart logind

- name: unattended-upgrades | restart systemd service
  service:
    name: unattended-upgrades.service
    daemon_reload: yes
    enabled: yes
    state: restarted
  listen: unattended-upgrades configuration changed
