---

#
# Below group/cluster vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#groupcluster-variables
#

# Use a specific version of k3s
k3s_release_version: "v1.19.4+k3s1"

# Install using hard links rather than symbolic links.
# ...if you are using the system-upgrade-controller you will need to use 
# hard links rather than symbolic links as the controller will not be able 
# to follow symbolic links.
k3s_install_hard_links: true

# Use experimental features (spooky!)
k3s_use_experimental: true

# Enable embedded etcd datastore
k3s_etcd_datastore: true

# Use a specific control node address. IP or FQDN.
k3s_control_node_address: roci.lanquarden.com

# Enable debugging
k3s_debug: false

# A list of auto deploying manifests templates
ha_vip_interface: eno1
ha_vip: 192.168.1.10

k3s_server_manifests_templates:
  - vip.yaml.j2

#
# Below ansible vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#ansible-controller-configuration-variables
#

# Escalate user privileges for all
k3s_become_for_all: true

#
# Below server vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration
#

# k3s server settings
k3s_server:
  disable:
    - traefik
    - servicelb

#
# Below agent vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#agent-worker-configuration
#

